config/routes.rb
Ruzzit::Application.routes.draw do
  devise_for :users, skip: [:sessions, :registrations]
  as :user do
    get     "signup"  => "devise/registrations#new",     as: :new_user_registration
    post    "signup"  => "devise/registrations#create",  as: :user_registration
    get     "signin"  => "devise/sessions#new",          as: :new_user_session
    post    "signin"  => "devise/sessions#create",       as: :user_session
    delete  "signout" => "devise/sessions#destroy",      as: :destroy_user_session
    get     "account" => "devise/registrations#edit",    as: :edit_user_registration
    patch   "account" => "devise/registrations#update",  as: ""
    put     "account" => "devise/registrations#update",  as: ""
    delete  "account" => "devise/registrations#destroy", as: ""
  end

  resources :ruzzes, only: [:index, :new, :create] do
    resources :likes, only: [:create, :destroy]
  end

  root "ruzzes#index"
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :asset, ImageUploader

  validates :asset, presence: true, integrity: true, processing: true

  before_save :update_asset_attributes

  has_one :ruzz, as: :attachable, dependent: :destroy
  accepts_nested_attributes_for :ruzz

private

  def update_asset_attributes
    if asset.present? && asset_changed?
      content_type = asset.file.content_type
      size = asset.file.size
    end
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :ruzz, counter_cache: true
  belongs_to :user
end

app/models/ruzz.rb
class Ruzz < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :user, touch: true
  belongs_to :attachable, polymorphic: true
  has_many :likes, dependent: :destroy

  scope :ordered_by_creation, ->(order = "DESC") do
    order("created_at #{order.upcase}")
  end

  def image_url
    attachable.asset_url unless attachable.nil?
  end

  def thumb_url
    attachable.asset_url(:thumb) unless attachable.nil?
  end

  def liked_by?(user)
    likes.where(user: user).first.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :ruzzes, dependent: :destroy
  has_many :likes, dependent: :destroy

  # :token_authenticatable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

  # Configure strong parameters for Devise controllers
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
  end

  # Configure path after signing in
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  # Configure path after signing out
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  respond_to :js

  before_action :authenticate_user!

  def create
    @like = Like.create(like_params)
    @ruzz = Ruzz.find(like_params[:ruzz_id])
    render :toggle
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy!
    @ruzz = Ruzz.find(params[:ruzz_id])
    render :toggle
  end

private

  def like_params
    params.require(:like).permit(:ruzz_id, :user_id)
  end
end

app/controllers/ruzzes_controller.rb
class RuzzesController < ApplicationController
  respond_to :html

  before_filter :authenticate_user!, except: :index

  def index
    @ruzzes = Ruzz.ordered_by_creation.page(params[:page])
  end

  def new
    @image = Image.new
    @ruzz = @image.build_ruzz(user_id: current_user.id)
  end

  def create
    @image = Image.new(image_params)
    @ruzz = @image.ruzz
    if @image.save
      redirect_to ruzzes_path
    else
      render :new
    end
  end

private

  def image_params
    params.require(:image).permit(
      :asset, :asset_cache, ruzz_attributes: [:name, :description, :user_id]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{:"data-dismiss" => "alert"} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "RuzziT", root_path, class: "brand brand-bootbus"

%button{type: "button", class: "btn btn-navbar", :"data-toggle" => "collapse", :"data-target" => ".nav-collapse"}
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar

.nav-collapse.collapse
  %ul{class: "nav pull-right"}
    - if user_signed_in?
      %li
        = link_to(new_ruzz_path, class: "btn-primary") do
          %i{class: "icon-pushpin"}
          Ruzz!
      %li
        = link_to(edit_user_registration_path) do
          %i{class: "icon-home"}
          Account
    - else
      %li
        = link_to(new_user_registration_path) do
          %i{class: "icon-user"}
          Sign up

    - if user_signed_in?
      %li
        = link_to(destroy_user_session_path, method: "delete") do
          %i{class: "icon-signout"}
          Sign out
    - else
      %li
        = link_to(new_user_session_path) do
          %i{class: "icon-signin"}
          Sign in

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %meta{content: content_for?(:description) ? yield(:description) : "RuzziT", name: "description"}/
    %meta{content: "Giannicola Olivadoti", name: "author"}/
    %title= content_for?(:title) ? yield(:title) : "RuzziT"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            = render "layouts/navigation"
    .content{role: "main"}
      .container
        = yield :page_header
        .row
          .span12
            = render "layouts/messages"
            = yield
    %footer
      .container
        .row
          .span12
            %p{class: "pull-right"}
              Powered by
              %strong Ruby on Rails
            %p
              © Copyright 2013 oli-g

app/views/likes/toggle.js.erb
$("li[data-id=<%= dom_id(@ruzz) %>]").replaceWith("<%= escape_javascript(render @ruzz) %>");
$("li[data-id=<%= dom_id(@ruzz) %>] form a").on("click", function(event) {
  event.preventDefault()
  $(this).closest("form").submit()
});

app/views/ruzzes/_ruzz.html.haml
%li.span3{data: { id: dom_id(ruzz) }}
  = link_to "#", class: "thumbnail" do
    = image_tag ruzz.thumb_url
  %strong
    = ruzz.user.full_name
  %span.pull-right
    %i{class: "icon-thumbs-up"}
    %span.likes_count
      = ruzz.likes_count
    - if user_signed_in?
      -if ruzz.liked_by?(current_user)
        = form_for [ruzz, ruzz.likes.where(user: current_user).first], html: { method: :delete }, remote: true do |f|
          = link_to "Unlike!", "#"
      - else
        = form_for [ruzz, ruzz.likes.build(user: current_user)], remote: true do |f|
          = f.hidden_field :ruzz_id
          = f.hidden_field :user_id
          = link_to "Like!", "#"

app/views/ruzzes/index.html.haml
= content_for :page_header do
  .page-header
    %h1
      Lookin' for some serious ruzz?
      %small RuzziT has it all!

%ul.thumbnails
  = render @ruzzes

= paginate @ruzzes

app/views/ruzzes/new.html.haml
= content_for :page_header do
  .page-header
    %h1
      Ruzz at your own risk

= simple_form_for @image, url: ruzzes_path do |f|
  = f.error_notification

  .inputs
    = f.input :asset
    = f.input :asset_cache, as: :hidden

    = f.simple_fields_for :ruzz_attributes do |r|
      = r.input :user_id, as: :hidden, input_html: { value: @ruzz.user_id }
      = r.input :name
      = r.input :description

  .actions
    = f.button :wrapped, "Ruzz!!!", class: "btn-primary"